### ISSUE TITLE
Support for other formats

### ISSUE THREAD

**Issue by michaelmior** [lbrayner/vim-rzip#12]
Any chance this could be extended to support other zipped formats? (e.g. gzip, bz2, xz, etc.)

**Comment by lbrayner** [comment]
Hey, I just looked into it. Vim has a _gzip_ plugin, which handles many compression formats (gz, xz, bz2); and a _tar_ plugin, which handles the archiving format **tar**. I'll consider extending those (it would be in another plugin, I guess), but I'm not familiar with them, since I rarely handle those formats.

**Comment by michaelmior** [comment]
Fair enough. I'm a total Vimscript noob, so I probably won't be investigating this myself any time soon. In any case, thanks for vim-rzip!

**Comment by lbrayner** [comment]
You're welcome!
