### ISSUE TITLE
Modifying a zip with a space in its name copies the zip file

### ISSUE THREAD

**Issue by rpocklington** [lbrayner/vim-rzip#13]
**Version Details**
vim
```VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug 17 2018 17:24:51)```

rzip
```" zip.vim version v27m-rzip```
rzip installed on commit `bf4efdd8c41a81b81f8446d8a261f8a5be5f131a`

OS X
```
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
```

**Description**

When modifying the contents of a zip file using `vi` and `rzip`, if the file has a space in its name, the changes do not save to the original file. Instead, they save to a file with the same name, except that spaces are replaced with a backslash followed by a space (`\ `). It appears that shell escaping/unescaping is not being processed correctly somewhere.

**Steps to Reproduce**

1. Create a dummy text file named "foo"
2. Add it to a zip file named "I have a space.zip"
3. Use `vi` to modify the contents of foo in "I have a space.zip"
4. Save changes and exit vi

Expected behavior:
* The contents of "I have a space.zip" are updated
* No new files have been created

Observed behavior:
* The contents of "I have a space.zip" are _not_ updated
* A new file named "I\ have\ a\ space.zip" is created, with contents matching what was expected for "I have a space.zip"

```
[rpocklington: ~/testchamber/rzip-with-space]$ echo "This is a test" > foo

[rpocklington: ~/testchamber/rzip-with-space]$ zip "I have a space.zip" foo
  adding: foo (stored 0%)

[rpocklington: ~/testchamber/rzip-with-space]$ ll
total 16
-rw-r--r--  1 rpocklington  staff  171 Jun  5 11:26 I have a space.zip
-rw-r--r--  1 rpocklington  staff   15 Jun  5 11:26 foo

[rpocklington: ~/testchamber/rzip-with-space]$ vi I\ have\ a\ space.zip

[rpocklington: ~/testchamber/rzip-with-space]$ ll
total 24
-rw-r--r--  1 rpocklington  staff  171 Jun  5 11:26 I have a space.zip
-rw-r--r--  1 rpocklington  staff  182 Jun  5 11:26 I\ have\ a\ space.zip
-rw-r--r--  1 rpocklington  staff   15 Jun  5 11:26 foo

[rpocklington: ~/testchamber/rzip-with-space]$
```

**Further Notes**

I've confirmed that this behavior is specific to `rzip`. I removed the `rzip` extension by renaming `~/.vim/pack/bundle/start/vim-rzip` to `~/.vim/pack/bundle/start/.vim-rzip.hide` and reran the steps to reproduce. The observed behavior matched expected behavior. I also noted that the `zip.vim version v27m-rzip` message at the top of the file in `vi` was replaced with a message specific to vim.

**Comment by lbrayner** [comment]
Thank you for reporting this. I'll get to it right away.

**Comment by lbrayner** [comment]
I was escaping the filename twice. 

https://github.com/lbrayner/vim-rzip/commit/ebcc13602006666d631624a7434e1cb74c95c52f fixes it.

I'll leave this open for now.

**Comment by rpocklington** [comment]
The behavior matches my expectations on commit `ebcc13602006666d631624a7434e1cb74c95c52f`.

**Comment by lbrayner** [comment]
As it turns out, this is a stopgap measure. The original code on which this is based has flaws when dealing with filenames across multiple platforms with the special wildcard characters that unzip accepts (*,? and the square brackets []). I'm only able to test on Windows & Linux.

A better solution is coming soon, be advised!

I think terminal Vim beahves almost exactly alike on Linux and on MacOS, right? Except for the case insensitivity.

**Comment by lbrayner** [comment]
Turns out what was missing was escaping the special characters (*,? and square brackets []) on Unix filesystems. Square brackets were already taken care of on Windows (I missed that) -- plus both * and ? are forbidden on NTFS (I was smashing my head over this for a bit).

https://github.com/lbrayner/vim-rzip/commit/ec2c5a5f6a308d9fab8561348f63a36ddb43898b
